export const mockWigs = [
  {
    id: "W001",
    barcode: "123456789",
    name: "Elegant Wave",
    style: "Wavy",
    length: "18 inches",
    color: "Dark Brown",
    hairType: "Human Hair",
    hairTexture: "Silky",
    size: "Medium",
    price: 299.99,
    status: "In Stock", // Sold/Hold status
    clientName: "",
    newOrder: false,
    location: "Shelf A1",
    costPrice: 150.00,
    receiveDate: "2024-01-15",
    soldDate: "",
    stock: 5,
  },
  {
    id: "W002",
    barcode: "987654321",
    name: "Sleek Straight",
    style: "Straight",
    length: "20 inches",
    color: "Black",
    hairType: "Synthetic",
    hairTexture: "Straight",
    size: "Large",
    price: 249.99,
    status: "Hold",
    clientName: "Jane Smith",
    newOrder: true,
    location: "Shelf B2",
    costPrice: 120.00,
    receiveDate: "2024-02-01",
    soldDate: "",
    stock: 8,
  },
  {
    id: "W003",
    barcode: "456789123",
    name: "Curly Dream",
    style: "Curly",
    length: "16 inches",
    color: "Auburn",
    hairType: "Human Hair",
    hairTexture: "Curly",
    size: "Small",
    price: 329.99,
    status: "Sold",
    clientName: "Mary Johnson",
    newOrder: false,
    location: "Shelf C3",
    costPrice: 180.00,
    receiveDate: "2024-01-20",
    soldDate: "2024-02-15",
    stock: 3,
  },
];