// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkhprhtewdasdgpoybzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxraHByaHRld2Rhc2RncG95YnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNzk0NjksImV4cCI6MjA0OTY1NTQ2OX0.XQH34M4IcSs2pv4DazBP7d1smWiHPdSDOc3N7eMoge4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);